#!/usr/bin/env bash

export bin=beach
export collection_path="$HOME/vendor/odin-sokol/sokol"
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
   export bin="beach.exe"
   export collection_path="$HOME/projects/sokol-odin/sokol"
fi

test -f beach && rm beach
#odin build ./src -debug -out:${bin}
odin build ./src -collection:sokol=${collection_path} -debug -out:${bin}
