#!/usr/bin/bash

dir="$1"
out="$2"

files=$(find $dir -maxdepth 1 -mindepth 1 -type f | sort) # find every file in the input dir
for file in $files; do
	if echo "$file" | grep -qv ".wav"; then
		continue
	fi

	echo "ffmpeg -i $file -c:a pcm_f32le $out/$(basename "$file")"
	ffmpeg -i "$file" -c:a pcm_f32le $out/$(basename "$file")
done


